filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: true
    reload.period: 30s

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
  - add_fields:
      when.network.source.address: 192.0.0.0/24
      fields:
          source.geo.location:
          lat: 13.7512
          lon: 100.5172
          source.geo.continent_name: Asia
          source.geo.country_iso_code: TH
          source.geo.region_iso_code:  TH-M
          source.geo.region_name: Bangkok
      target: '' 

processors:
 - drop_fields.fields: ['event.timezone']
 - add_fields:
    target: event
    fields:
     timezone: 'Asia/Bangkok'
filebeat.overwrite_pipelines: true
output.elasticsearch: 
  hosts: ["https://localhost:9200"]
  pipeline: geoip-info
  index: "sec-siem-suricata-%{+YYYY.MM.dd}"
  protocol: "https"
  username: ${USERNAMEES}
  password: ${PASSWORDES}
  allow_older_versions: true
  ssl:
    enabled: true
    verification_mode: "none"
#true or false data-streams
setup.template.enabled: true
setup.ilm.enabled: false
setup.template.overwrite: true
setup.template.name: "sec-siem"
setup.template.pattern: "sec-siem-dev-suricata-*"
setup.kibana:
  host: "${KIBANAHOST}"
setup.dashboards.index: "sec-siem-*"
setup.dashboards.enabled: false
setup.kibana.ssl.enabled: true
setup.kibana.ssl.verification_mode: "none"
